export const DAILY_REPORT_REQ = 'DAILY_REPORT_REQ'; 
export const DAILY_REPORT_SUCCESS = 'DAILY_REPORT_SUCCESS'; 
export const DAILY_REPORT_FAIL = 'DAILY_REPORT_FAIL'; 

export const PATENT_REPORT_REQ = 'PATENT_REPORT_REQ'; 
export const PATENT_REPORT_SUCCESS = 'PATENT_REPORT_SUCCESS'; 
export const PATENT_REPORT_FAIL = 'PATENT_REPORT_FAIL'; 
