export const getAmbulanceType = {
    REQUEST:"GET_AMBULANCE_REQUEST",
    SUCCESS:"GET_AMBULANCE_SUCCESS",
    ERROR:"GET_AMBULANCE_ERROR",
};

export const createAmbulanceCrewType = {
    REQUEST:"CREATE_AMBULANCE_CREW_REQUEST",
    SUCCESS:"CREATE_AMBULANCE_CREW_SUCCESS",
    ERROR:"CREATE_AMBULANCE_CREW_ERROR",
}

export const createAmbulanceType = {
    REQUEST:"CREATE_AMBULANCE_REQUEST",
    SUCCESS:"CREATE_AMBULANCE_SUCCESS",
    ERROR:"CREATE_AMBULANCE_ERROR",
}