export const DROPDOWN_LIST_REQ = 'DROPDOWN_LIST_REQ';
export const DROPDOWN_LIST_SUCCESS = 'DROPDOWN_LIST_SUCCESS';
export const DROPDOWN_LIST_FAIL = 'DROPDOWN_LIST_FAIL';

export const STATE_DROPDOWN_REQ = 'STATE_DROPDOWN_REQ';
export const STATE_DROPDOWN_SUCCESS = 'STATE_DROPDOWN_SUCCESS';
export const STATE_DROPDOWN_FAIL = 'STATE_DROPDOWN_FAIL';
